### ISSUE TITLE
Snapshot repository doesn't include the newer versions

### ISSUE THREAD

**Issue by games647** [git-commit-id/maven-git-commit-id-plugin#344]
The snapshot repository only contains versions for 2.0.5, but I want to use a feature from 2.2.4. Could you update the builds on that repository or is there another way to use the unreleased 2.2.4 version (except building it manually)?

**Comment by TheSnoozer** [comment]
Even though its on the readme it doesn't seem to be used. It seems that it was exactly used for one snapshot deploy back in 2012 (https://oss.sonatype.org/content/repositories/snapshots/pl/project13/maven/git-commit-id-plugin).

I get your point why you might want to have this as convenient way...I'll see if there is anything automatic that could be used to always deploy the latest and greatest.

If there is no such automatic process I feel it would be too tedious to always deploy the latest snapshot....or just when being asked doesn't sound right as well.....debating this with myself since it seems this might even be an option too since the last ask was back in 2012...so one deploy every 5 years sounds reasonable for doing it manually. However manually would then not always deliver the latest and greatest. Honestly not sure if something automated would be way over the top for the ask here, but it feels like this would be the most accurate and the right solution for this.

**Comment by TheSnoozer** [comment]
Why did you close this?
It is not fixed properly (yet)....
