### ISSUE TITLE
Wrong properties values when building under Hudson

### ISSUE THREAD

**Issue by pauloneves** [git-commit-id/maven-git-commit-id-plugin#370]
The plugin is generating wrong values when running under Hudson. It works fine when I run it in my local machine. 

It looks like it is related to the issue #325

Below is the generated git.properties with some comments. 

```
#Generated by Git-Commit-Id-Plugin
#Thu Jul 05 19:58:18 BRT 2018
git.branch=43bb4ef9f75d2c88217ff3aa27288b240fdc256a #not the branch, but a commit hash
git.build.host=correct
git.build.time=2018-07-05T19\:38\:57-0300
git.build.version=1.4.96-SNAPSHOT #correct from maven
git.closest.tag.commit.count=0 #always zero
git.closest.tag.name=hudson-<my job name>-<build  number> #always wrong
git.commit.id=ad684aaa425b293046eca3ca73bd199d80b9fc62 #different from above
git.commit.id.abbrev=ad684aa
git.commit.id.describe=hudson-<my job name>-<build  number> # as above
git.commit.id.describe-short=hudson-<my job name>-<build  number> #as above
git.commit.time=2018-07-05T19\:02\:04-0300
git.dirty=false
git.remote.origin.url=correct
git.tags=hudson-<my job name>-<build  number> # as above
```
First error:
git.branch is the commit hash of the HEAD of the branch. In my job the branch to build is configured as `**` (to build all the branches). If I fix a branch in this parameter it displays the branch name correctly. 

All these parameters are incorrect with the same value:
git.closest.tag, git.closest.tag.name, git.commit.id.describe

They have the exact same value that is in the Hudson env variable `BUILD_TAG`, that is: a fixed prefix `hudson-`, concatenated with the job name + '-' + the build number.

I'm using a very old Hudson version.

Below is my plugin configuration. I tried with <useNativeGit> as true and false and got the same (wrong) result. 

```
      	    <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>2.2.4</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <dotGitDirectory>${project.basedir}/../.git</dotGitDirectory>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>

                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>

                    <excludeProperties>
                      <excludeProperty>git.*.user.*</excludeProperty>
                      <excludeProperty>git.commit.message.*</excludeProperty>
                    </excludeProperties>

                    <useNativeGit>true</useNativeGit>
                    <evaluateOnCommit>HEAD</evaluateOnCommit>
                    <verbose>true</verbose>
                </configuration>

            </plugin>
```
It is a multimodule project, and this configuration is in the pom parent. All submodules generate their git.properties file. 

I have the verbose output here and can send it by email if you wish. I don't want to post here some of my company info.

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your issue here.
Let me try to elaborate on each of the reported issues.
1. 
> git.branch is the commit hash of the HEAD of the branch

CI builds are usually done in detached HEAD state (https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit) and thus essentially make it impossible to know on what branch we are.The workaround trick that this plugin is doing to get the branch is to extract environment variables exposed by the CI-Build.

> In my job the branch to build is configured as ** (to build all the branches). If I fix a branch in this parameter it displays the branch name correctly.

Does the configuration of ``** (to build all the branches)`` launches a single build that builds through all branches? Or is it just that hudson "listens" to changes on all branches and builds them in a single build once it detected a change? Not sure how Hudson behaves here...maybe it would help in specific if you could elaborate what type of setup you have so I could get a better understanding (single job with just the ``**`` branch config? pipeline configuration?

2.
> All these parameters are incorrect with the same value:
> git.closest.tag, git.closest.tag.name, git.commit.id.describe
> 
> They have the exact same value that is in the Hudson env variable BUILD_TAG, that is: a fixed prefix hudson-, concatenated with the job name + '-' + the build number.

That sounds like Hudson is creating tags for each build and thus altering the local checkout of the clone. There should be a configuration (somewhere) in the job that controls if Hudson should create tags for each build (similar to http://www.benhallbenhall.com/2013/03/hudson-jenkins-create-git-tags-branches-automatically/).
By the looks I would tend to say this is a misconfiguration and the plugin is getting the 'right' information, that have been injected at a wrong place. It should be easy to login into hudson via SSH, go to the directory where the checkout is, and simply do a `git describe --long`. I would suspect this returns similar tag names as the plugin (if so it is a job misconfiguration)

3. 
> It is a multimodule project, and this configuration is in the pom parent. All submodules generate their git.properties file.

You may or (may not) want to add ```<runOnlyOnce>true</runOnlyOnce>``` to the plugin configuration.

From the Readme:
>

4.
> I'm using a very old Hudson version.
Whats the version you are using? :-)

**Comment by TheSnoozer** [comment]
I'm closing this. since I don't see a particular issue within the plugin.
If you provide a pointer to a specif problem I'd be happy to look into it.
