### ISSUE TITLE
AdditionalProperties support? like  Additional properties to store in the build-info.properties.

### ISSUE THREAD

**Issue by 15168326318** [git-commit-id/maven-git-commit-id-plugin#402]

**Comment by TheSnoozer** [comment]
Hi,
thanks for opening an issue for this.
Just to understand this correctly -- you are asking for some sort of support to add more custom properties to the generated properties-file?

In general I would not so sure if I want to add support for that, since this somewhat feels like a misuse of this plugin. But on the other hand, we are already doing a lot of stuff that is not directly related to only the git world. By adding such feature, we would surely open the plugin to be more 'general'.

In general what would make me fight back against such suggestion, is the fact that I think what you are asking could be achieved by 
* using maven's resource filtering. In particular this plugin allows to expose the properties not only to the generated file, but they can also be exposed to the maven world (e.g. with `<injectAllReactorProjects>true</injectAllReactorProjects>`). One way of achieving what you are asking is to have this plugin run in the `initialize` phase, and a [custom copy resource execution](https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html) [in any later phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference) (e.g. `generate-sources`). The `copy resource` execution would copy whatever pre-crafted property file into the right place.
* or by using one of the `property file writer plugins` (see: https://stackoverflow.com/a/37650756)


Could you confirm if I understood the use-case correctly?

**Comment by veenarm** [comment]
We want to inject git.pipeline into the file, (To show which pipeline ID was triggered for this build process) (

**Comment by TheSnoozer** [comment]
What build ci / or tool do you use?

Just to mention it, this plugin already exposes certain properties that are CI related (see for example the [GitlabBuildServerData](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/afff161d1efecdbc519529106df3dd27bb5664f5/src/main/java/pl/project13/maven/git/build/GitlabBuildServerData.java#L44))

**Comment by veenarm** [comment]
Gitlab ci docker and Jenkins slaves.

I'm using the plugin but that's not an output car that we see, is there a config to enable it?

**Comment by TheSnoozer** [comment]
The plugin tries to extract the property when it is detecting that it is being executed within a CI build.

I'd suggest for troubleshooting a two way approach.
First I would check if the environment variables are set within the job so the plugin can detect if it is running within a Gitlab CI / Jenkins build. For troubleshooting I'd recommend to run `printenv` (or similar) within the ci build. 

Second I would check if the properties are set in order to have this plugin detect if it's running within a CI build.

If you run on Gitlab the [GitlabBuildServerData](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/afff161d1efecdbc519529106df3dd27bb5664f5/src/main/java/pl/project13/maven/git/build/GitlabBuildServerData.java#L44) is the piece that attempts to detect if it is running within a Gitlab CI. In order to result true here the environment property `CI` must be set and the environment property `CI_PIPELINE_ID` and/or `CI_PIPELINE_IID` contains the information you desire.

If you run on Hudson or Jenkins the [HudsonJenkinsBuildServerData](https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/afff161d1efecdbc519529106df3dd27bb5664f5/src/main/java/pl/project13/maven/git/build/HudsonJenkinsBuildServerData.java#L39) is the piece that attempts to detect if it is running within a Hudson/Jenkins CI. In order to result true here the environment property `JENKINS_URL` / `JENKINS_HOME` must be set and the environment property `BUILD_NUMBER` contains the information you desire.

For troubleshooting from the plugin perspective try to enable enable verbose mode (e.g. ``<verbose>true</verbose>``) and ensure that your `excludeProperties` do not list the `build.number*` properties. If you have `includeOnlyProperties` configured make sure to add them there (otherwise they will be filtered out). For testing it might be easier to just **temporarily** remove the `excludeProperties`/ `includeOnlyProperties` (make sure to put it back afterwards).

Also make sure that you at least run the plugin with `<version>2.2.5</version>` or even the latest `<version>3.0.0</version>`.

**Comment by veenarm** [comment]
Ah, seems we're using 2.2.4 as I added the CI var and it didn't trigger.

**Comment by veenarm** [comment]
Hey mate, we upgraded to 3.0.0 and it's now adding those properties from GITLAB perfelect. Thankyou for your assistance :)

**Comment by TheSnoozer** [comment]
Thanks for the confirmation mate :-)

Glad its working and I'm going ahead and close this issue. If you encounter any other problem please feel free to open a new one :-)
