### ISSUE TITLE
USERAUTH fail

### ISSUE THREAD

**Issue by VK2BEA** [git-commit-id/maven-git-commit-id-plugin#446]
This is probably not a bug (perhaps a configuration issue) but I get this error when when I package the war for my project.

```
[INFO] Collected git.closest.tag.commit.count with value 119
[INFO] Collected git.total.commit.count with value 340
[ERROR] Failed to perform fetch
org.eclipse.jgit.api.errors.TransportException: ssh://git@my.repo.com/myProject: USERAUTH fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:254)
	at pl.project13.maven.git.JGitProvider.fetch(JGitProvider.java:352)
	at pl.project13.maven.git.JGitProvider.getAheadBehind(JGitProvider.java:339)
        ....
```
My ssh key is loaded by the ssh-agent and I can use git to pull and push to the repository.

**Comment by TheSnoozer** [comment]
Hello,
thank you for reporting your problem here.
That indeed looks interesting and by searching for `jgit USERAUTH fail` I get the impression that this could happen if you use a ssh-key with passphrase (is this the case?) [References [here](https://stackoverflow.com/questions/45889326/userauth-fail-using-jgit-to-access-git-repo-securely-for-pullcommand) and [here](https://stackoverflow.com/questions/45889326/userauth-fail-using-jgit-to-access-git-repo-securely-for-pullcommand/45945238)].

Are you using Windows?

Perhaps could you also try using the native git binary (via `<useNativeGit>true</useNativeGit>`).

If this does not solve the issue you should be able to turn off the `fetch` operation by setting `<offline>true</offline>`.

**Comment by VK2BEA** [comment]
...yes `<useNativeGit>true</useNativeGit> ` did the trick!

Thanks a million..

**Comment by TheSnoozer** [comment]
Thanks for the quick feedback!
Glad it's working....not sure why jgit (java implementation of git) doesn't like it....but I guess that's why this plugin also has the native implementation :-)

**Comment by VonUniGE** [comment]
You can also set in the configuration:
`<offline>true</offline>`

**Comment by TheSnoozer** [comment]
Thanks! I added this to the release notes.....I still wonder why this suddenly starts to happen (perhaps more users now use the version that fetches the upstream repo)...
